--
-- Archivo generado con SQLiteStudio v3.4.17 el jue. mar. 20 16:21:17 2025
--
-- Codificación de texto usada: UTF-8
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Tabla: Duenio
CREATE TABLE Duenio (
    id      INTEGER,
    nombre  TEXT,
    paterno TEXT,
    materno TEXT,
    CI      TEXT
);

INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (1, 'MARY CANDELARIA', 'VILLAR', 'CARDENAS', '3509303 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (2, 'ZENOBIO ', 'PICAVIA', 'MEJIA', '483941 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (3, 'CHELA ', 'AGUILAR', 'DE VALDEZ', '2136903 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (4, 'GUILLERMO ', 'SILES', 'JIMENEZ', '70874 LP');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (5, 'OTILIA ALEJANDRINA', 'BOLIVAR', 'VDA. DE PICAVIA', '2492406 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (6, 'EMETERIO ', 'LAURA', 'INCA', '6091940 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (7, 'AREA DE', 'EQUIPAMIENTO', NULL, '91');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (8, 'GENOVEVA ', 'NAVARRO', 'DE MENA', '90');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (9, 'DORA ', 'JIMENEZ', 'DE CORNEJO', '2680298 LP');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (10, 'JUAN ', 'MORALES', 'IPORRE', '3509306 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (11, 'CARDENIO ', 'LAURA', 'SELIZ', '2796865 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (12, 'YOYI ', 'LAURA', 'CELIS', '4884030 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (13, 'MARGOT ', 'CARDENAS', 'CELIS', '4305084 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (14, 'WILLY ', 'AGUILAR', 'GONZALES', '2248095 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (15, 'AREA VERDE', NULL, NULL, '89');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (16, 'LUIS ', 'BUSTILLOS', 'BUSTILLOS', '617761 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (17, 'JULIA ', 'PEREA', 'DE SELAES', '2363996 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (18, 'RAMONA ', 'TAPIA', 'LUQUE', '2245037 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (19, 'NESTOR ', 'MIRANDA', 'CABEROS', '279404 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (20, 'ABRAHAM ', 'MIRANDA', 'MAYTA', '4322696 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (21, 'IGLESIA LAS', 'ASAMBLEAS', 'DE DIOS', '88');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (22, 'FLORIAN ', 'MIRANDA', 'VEIZAGA', '6089610 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (23, 'ELIAS ', 'FORONDA', 'MERIDA', '699404 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (24, 'DANIEL ', 'MIRANDA', 'PICABIA', '2136900 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (25, 'PLAZUELITA CIRCUATA', NULL, NULL, '87');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (26, 'YHOCET AMANDA', 'ENDARA', 'CELIS', '7174902 TJ.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (27, 'IRENE ', 'SOLARES', 'CHURA', '6091921 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (28, 'SONIA ', 'PEREA', 'DE CHAMBI', '2244933 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (29, 'RIGOBERTO ', 'JIMENEZ', 'RODRIGUEZ', '2248094 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (30, 'GENARA ', 'COCA', 'NAVIA', '9912334 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (31, 'MAVEL SUSANA', 'GUTIERREZ', 'MAMANI', '6757729 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (32, 'GERMAN ', 'COCA', 'LOZA', '86');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (33, 'GILBERTO ROLANDO', 'PICAVIA', 'ENRRIQUEZ', '7743798 SC.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (34, 'ROMAN ', 'COCA', 'NAVIA', '2136987 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (35, 'MARIA LUZ', 'ASTURIZAGA', 'QUISPE', '4316022');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (36, 'ANGEL ', 'PICAVIA', NULL, '2796999 OR');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (37, 'ANGELA ', 'PANI', 'ULLOA', '6091923 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (38, 'ASCENCIO ', 'ALANOCA', 'CHOQUE', '6091924 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (39, 'FLORA ', 'COSSIO', 'VEIZAGA', '2317367 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (40, 'MELINDA GLADYS', 'CHUQUIMIA', 'ALI', '8394726 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (41, 'DEYNA ALIDA', 'CHUQUIMIA', 'ALI', '8394729 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (42, 'OGEID HUASCAR', 'CHUQUIMIA', 'ALI', '13643201 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (43, 'GLICERIO FILIMON', 'QUISPE', 'GUTIERREZ', '2248079 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (44, 'ANIBAL WILDER', 'PICAVIA', 'COSSIO', '9911546 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (45, 'MARCIAL ', 'APAZA', 'ESTRADA', '13344341 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (46, 'NOLBERTO ', 'APAZA', 'ESTRADA', '4902718 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (47, 'PAULINO ', 'BERRIOS', 'MIRANDA', '643364 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (48, 'IRENE ', 'PICAVIA', 'FERNANDEZ', '2796832 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (49, 'CARMELA ', 'ZEBALLOS', 'MENCIA', '3508039 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (50, 'TEODOMIRO ', 'MACHICADO', 'ARGOLLO', '9911549 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (51, 'YESENIA ROSARIO', 'RODRIGUEZ', 'PEREA', '3318178 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (52, 'SAUL HERIBERTO', 'SELAES', 'PEREA', '3318177 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (53, 'PABLO ', 'QUIROGA', 'MANZANO', '6997054 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (54, 'NICOLASA ', 'CHOQUE', 'VDA. DE ROMERO', '2136809 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (55, 'LEONORA ', 'COCA', 'VEIZAGA', '9912768 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (56, 'VICTOR ARCENIO', 'PICAVIA', 'ENRRIQUEZ', '6997040 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (57, 'BANEZA ', 'VILLEGAS', 'ARI', '9060799 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (58, 'BRAYAN ', 'PASTEN', 'CHAVEZ', '9060549 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (59, 'JOSE ', 'MORALES', 'NABARRO', '6999411 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (60, 'AGUSTINA ', 'CRUZ', 'CHOQUE', '9060781 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (61, 'ELEUTERIA ', 'MARCA', 'MAMANI', '14038910 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (62, 'JOSE LUIS', 'MORALES', 'MARCA', '10095607 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (63, 'JUAN PABLO', 'MORALES', 'MARCA', '10095606 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (64, 'HERMINIA ', 'ARDAYA', 'SALVADOR', '2416533 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (65, 'ARTURO ', 'HUARACHI', 'QUISPE', '648064 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (66, 'EDWIN ', 'COSSIO', 'LOZA', '4935104 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (67, 'JOSE LUIS', 'COSSIO', 'LOZA', '4787707 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (68, 'FLAVIA CAROLINA', 'ARUQUIPA', 'AYCA', '9912255 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (69, 'SEVERINO ', 'AYCA', 'MAMANI', '6091935 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (70, 'EDMUNDO ', 'COSSIO', 'BUTRON', '2017987 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (71, 'SANTIAGO ', 'LIMA', 'FERNANDEZ', '7299088 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (72, 'LEONE ', 'COCA', 'VEIZAGA', '5042680 TJ.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (73, 'EVANGELINA COCA', 'DE', 'PATINO', '9912263 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (74, 'FELIPA ', 'COCA', 'VEIZAGA', '6997059 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (75, 'CRUZ ', 'SACA', 'ZAMBRANA', '2008502 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (76, 'HUASCAR JULIO', 'SACA', 'MAMANI', '16775751 QR');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (77, 'JUNTA DE', 'VECINOS', 'DE VECINOS', '85');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (78, 'BRIGITTE GEYDY', 'AGUIRRE', 'CAMPOS', '7941436 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (79, 'CHARLES AMBAR', 'AGUIRRE', 'CAMPOS', '8684353 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (80, 'MARIA ELENA', 'CHOQUE', 'RAMOS', '9406814 JHONNY');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (81, 'RICHARD ', 'ACHO', 'CORIA', '9060668 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (82, 'JULIO ', 'ACHO', 'DELGADO', '6705048 PT.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (83, 'LUIS ', 'COCA', 'LOZA', '6999407 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (84, 'FELIZA ', 'CALIZAYA', 'MAMANI', '3569733 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (85, ' VICTORIA', 'CORANI', 'NAVIA', '9060601 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (86, 'MARIELA ', 'DURAN', 'SOLARES', '6816299 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (87, 'ELBIO ', 'DURAN', 'SOLARES', '6107681 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (88, 'FABIANA ', 'ARI', 'MIRANDA', '2148375 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (89, 'ROSA ', 'PASTEN', 'MAMANI', '4919104 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (90, 'EXALTO ', 'PASTEN', 'ARI', '9196078 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (91, 'MAXIMA ', 'CAMPOS', 'RUEDA', '3464764 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (92, 'DEMETRIO ', 'FLORES', 'VILLALOBOS', '2247713 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (93, 'HIPOLITA ', 'ARDAYA', 'SALVADOR', '3806969 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (94, 'PEDRO ', 'CAMPOS', 'RUEDA', '4778572 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (95, 'RITA ', 'RUEDA', 'VDA. DE CAMPOS', '2136991 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (96, 'JHOAN PAOLO', 'MIRANDA', 'ARUQUIPA', '8394716 QR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (97, 'ELVIS ', 'MAURIEL', 'VILLEGAS', '9060718 QR');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (98, 'RAUL IVAN', 'PAREDES', 'JACINTO', '13119362 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (99, 'RAUL FERNANDO', 'MORALES', 'SIPE', '9060709 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (100, 'NICOLAS ', 'AGUILAR', 'BOYAN', '2245019 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (101, 'PABLO FRANCISCO', 'MUNOZ', 'QUISBERT', '9060571 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (102, 'HEIDY ', 'CALLEJAS', 'RODRIGUEZ', '6121323 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (103, 'JUNTA DE', 'VECINOS', NULL, '84');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (104, 'RAMIRO ', 'AYAVIRI', NULL, '6275491 SC.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (105, 'CRISTIAN ', 'MACHICADO', 'HILARIO', '9060585 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (106, 'MAGDALENA ', 'CAMPOS', 'RUEDA', '6101755 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (107, 'LUIS ', 'MALLEA', 'PACHECO', '6502419 CB.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (108, 'AREA VERDE', NULL, NULL, '83');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (109, 'ALBERTO EMILIO', 'VARGAS', 'GOMEZ', '483920 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (110, 'JULIO ', 'MENESES', 'COLQUE', '9912481 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (111, 'ALCIRA ', 'ESCOBAR', 'VDA. DE HERRERA', '2236624 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (112, 'ROSALIA ', 'ESCOBAR', 'AGUILAR', '634131 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (113, 'LUIS MARIO', 'ESCOBAR', 'AGUILAR', '392859 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (114, 'NOEMY ', 'COSSIO', 'LOZA', '4926154 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (115, 'SEVERINO ', 'AYCA', 'MAMANI', '60911935 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (116, 'LORENZA MAMANI', 'DELGADO', 'DE BONIFACIO', '2796849 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (117, 'SERAFIN ', 'GUIZADA', 'ARDAYA', '5949578 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (118, 'FELIZA ', 'MAMANI', 'DELGADO', '12807183 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (119, 'CARLOS ', 'MAMANI', 'COSSIO', '6835559 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (120, 'IVAN ', 'GUIZADA', 'ARDAYA', '9867468 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (121, 'VICTOR HUGO', 'PICAVIA', 'FERNANDEZ', '3460114 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (122, 'HERNAN GONZALO', 'CALLE', 'CADENA', '6997079 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (123, 'SANTIAGO ', 'SOLARES', NULL, '5990233 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (124, 'JULIO ', 'MAMANI', 'GOMEZ', '2481410 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (125, 'SILVERIO ', 'GUIZADA', 'ARDAYA', '6997062 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (126, 'ADELIO ', 'GUIZADA', 'ARDAYA', '6997061 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (127, 'PABLO ', 'CHAMBI', 'MARCA', '9060778 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (128, 'ELOY ', 'CHAMBI', 'FLORES', '12736713 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (129, 'MONICA HERMINIA', 'FLORES', 'SANTOS', '8158669 SC.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (130, 'RUFINA ', 'ALANOCA', 'GARCIA', '5998589 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (131, 'ROSALIA ', 'ALIAGA', 'ALANOCA', '9061116 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (132, 'RONALD ABEL', 'CHAMBI', 'GUTIERREZ', '9060742 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (133, 'RICARDO RICHART', 'PICAVIA', 'ENRRIQUEZ', '9060746 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (134, 'CANDELARIA ', 'DELGADO', 'CORALES', '9912779 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (135, 'CARDENIO ', 'ADALID', 'PICAVIA', '9911552 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (136, 'ELISABET MARGARITA', 'PICABIA', 'FERNANDEZ', ' ELISABET');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (137, 'JUAN ', 'QUISPE', 'VILLA', '3351467 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (138, 'MAXIMILIANO JORGE', 'ALVAREZ', 'SERRANO', '6048983 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (139, 'ELBIRA JIMENA', 'MAMANI', 'APAZA', '6757728 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (140, 'OLIMPIA MERCELINA', 'FLORES', 'SANTOS', '6997057 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (141, 'WALDO ', 'RODRIGUEZ', 'RODRIGUEZ', '2248099 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (142, 'SATURNINO ', 'MEJIA', 'MAMANI', '9912258 LP');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (143, 'MONICA HERMINIA', 'FLORES', 'SANTOS', '8158669 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (144, 'DIEGO ', 'MAMANI', 'CONDORI', '82');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (145, 'MARIBEL ', 'NAVARRO', 'RUEDA', '53574899 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (146, 'WILFREDO FERNANDO', 'PICAVIA', 'ENRRIQUEZ', '7743764 SC.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (147, 'JUNTA DE', 'VECINOS', 'DE VECINOS', '81');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (148, 'JHONNY ', 'GRANADINO', 'RUEDA', '8394733 QR');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (149, 'JHAMIL ', 'ZAMBRANA', 'SILES', '6441586 CB.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (150, 'ISRAEL ', 'CALAMANI', 'NINA', '6941496 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (151, 'EDMUNDO ', 'MIRANDA', 'GUZMAN', '656374 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (152, 'ALBERTINA ', 'CARDOZO', 'NAVIA', '2248089 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (153, 'FILEMON BENITO', 'MAMANI', 'MARCA', '5482629 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (154, 'GABRIEL ', 'MORALES', 'CAVEZAS', '6101442 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (155, 'NELI ', 'APAZA', 'JAUREGUI', '5948179 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (156, 'NORCA ', 'SILES', 'MERCADO', '2245093 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (157, 'CLAUDINA ', 'FERNANDEZ', 'TICONA', '8328706 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (158, 'SANDRA NINOSCA', 'SILES', 'MERCADO', '5990183 LP');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (159, 'MARY CANDELARIA', 'VILLAR', 'CARDENAS', '3509313 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (160, 'DAVID ', 'MALLEA', NULL, '5990214 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (161, 'ROBERTO ', 'GUTIERREZ', 'AGUILAR', '2244958 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (162, 'WILSON ', 'SOLARES', 'MAMANI', '9060800 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (163, 'URBANO WINDSOR', 'PANI', 'YUJRA', '9912733 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (164, 'YENO ', 'MIRANDA', 'BOYAN', '2248086 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (165, 'NOEL ', 'MIRANDA', 'BOYAN', '2248087 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (166, 'AREA DE', 'EQUIPAMIENTO', 'PISCINA', '80');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (167, 'EDDY ', 'LOZA', 'RIOS', '4788678 L.P.MABEL');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (168, 'JULIAN ', 'MUNOZ', 'PACHECO', '2148317 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (169, 'ROLANDO ', 'MIRANDA', 'VEIZAGA', '5991066 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (170, 'JHOVANNA ', 'MORALES', 'MARCA', '6554450 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (171, 'MARIO HELMER', 'LAURA', 'PICAVIA', '4837114 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (172, 'DEMETRIO ', 'VILLEGAS', 'LADIOS', '2136455 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (173, 'GUILLERMO ', 'CHAMBI', 'FLORES', '2248079-1Q LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (174, 'CELIA RUEDA', 'REINAGA', 'VDA. DE NAVARRO', '5728216 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (175, 'GUSMAN ORLANDO', 'NAVIA', 'MUNOZ', '6116620 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (176, 'ASBEL ', 'MIRANDA', 'PICABIA', '5975333 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (177, 'AREA DE ', 'EQUIPAMIENTO', 'BAÑO PUBLICO', '79');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (178, 'EDDY ', 'LOZA', 'RIOS', '4788678 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (179, 'LIDIA ', 'CELIS', 'ESCOBAR', '3743333 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (180, 'EMILIO ', 'MEJIA', 'MENA', '9189926 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (181, 'VITA ISABEL', 'QUISPE', 'GUTIERREZ', '2248081 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (182, 'FELIX CEVERINO', 'AGUIRRE', 'MIRANDA', '10089246 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (183, 'ELISABET MARGARITA', 'PICABIA', 'FERNANDEZ', '4267101 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (184, 'ESTANISLAO ', 'COSSIO', 'LOZA', '6096444 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (185, 'CELIA ', 'NINA', 'CALLISAYA', '6948242 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (186, 'ROSSEMARY ', 'FARRACHOL', 'CARDOZO DE CHOQUE', '2796839 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (187, 'MELITON ', 'SILES', 'FERRUFINO', '279406 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (188, 'NELSO ', 'AGUIRRE', 'MIRANDA', '9504920 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (189, 'ALICIA ', 'CALAMANI', 'DE MEJIA', '8364332 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (190, 'ZULEGNA ', 'PICAVIA', 'VDA. DE LAURA', '2477944 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (191, 'VIVIENDAS PARA', 'PROFESORES', NULL, '78');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (192, 'MARUJA ', 'MARCA', 'ESCOBAR', '9912345 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (193, 'EMILIANA ', 'MIRANDA', 'PICABIA', '8363549 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (194, 'WILLIAM ', 'MIRANDA', 'PICABIA', '2409765 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (195, 'GROBER IVAN', 'VALDEZ', 'AGUILAR', '77');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (196, 'GUIMER DEMETRIO', 'RAMOS', 'MIRANDA', '6839893 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (197, 'MARINA ', 'DE MUNOZ', NULL, '76');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (198, 'LOURDES ', 'LEON', 'CHURA', '2136935 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (199, 'ERNESTINA ', 'MIRANDA', 'PICABIA DE NUNEZ', '7283619 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (200, 'FRANCISCA ', 'ARROYO', 'CRESPO', '7882527 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (201, 'TIBURCIO ', 'LUPINTA', 'CRESPO', '2245039 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (202, 'AREA DE', 'EQUIPAMIENTO', NULL, '75');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (203, 'MARCO ANTONIO', 'NINA', 'ROCHA', '9060547 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (204, 'PASCUAL ', 'ROCHA', 'PINTO', '10089245 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (205, 'CASA PARROQUIAL', NULL, NULL, '74');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (206, 'SALUSTIO ', 'AGUILAR', 'BOYAN', '2136906 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (207, 'GRACIELA ', 'TANGORA', 'GUTIERREZ', '2298866 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (208, 'MARIO ', 'SURITA', 'CAMPOS', '2244987 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (209, 'YOLA ', 'CARDENAS', 'DE VILLAR', '2137048 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (210, 'JUAN CARLOS', 'CELIS', 'PANUNI', '4308032 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (211, 'SEDE SOCIAL', 'CIRCUATA', NULL, '73');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (212, 'IGLESIA ', NULL, NULL, '72');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (213, 'MARTHA ', 'TANGORA', 'DE RODRIGUEZ', '3056001 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (214, 'AUGUSTO ', 'PACHECO', 'CARVAJAL', '337615 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (215, 'JUNTA DE', 'VECINOS', 'DE VECINOS', '71');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (216, 'JUNTA DE', 'VECINOS', NULL, '70');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (217, 'BERTA ', 'BOYAN', 'DE MIRANDA', '2136811 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (218, 'AREA DE', 'EQUIPAMIENTO', NULL, '69');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (219, 'ELIAS ZURITA', NULL, NULL, '68');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (220, 'ALFREDO ', 'MIRANDA', 'CAVEROS', '2680295 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (221, 'INGRITT ', 'PEREZ', 'CARDENAS', '4247196 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (222, 'ALCIRA ', 'ESCOBAR', 'VDA. DE HERRERA', '392859 L.P..');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (223, 'CASTO ENRRIQUE', 'AGUILAR', 'GONZALES', '2343626 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (224, 'MATADERO MUNICIPAL', NULL, NULL, '67');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (225, 'BAÑO ', NULL, NULL, '66');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (226, 'DAMIAN ', 'CALDERON', 'MORALES', '483851 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (227, 'CANDELARIA ', 'CALLEJAS', 'SULLCANI', '3787548 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (228, 'JUSTINA ', 'ONOSTRE', 'DE BOYAN', '2495603 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (229, 'GILARY MELL', 'RUEDA', 'MARCA', '6999458 QR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (230, ' ROSALIA', 'ESCOBAR', 'AGUILAR', '634131 QR');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (231, 'NELIDA ', 'ESCALERA', 'DE NOGALES', '3599668 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (232, 'NELSY MABEL', 'PICAVIA', 'DE APAZA', '6817345 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (233, 'ADOLFO RENE', 'PICAVIA', 'COSSIO', '8990790 SC.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (234, 'AGUSTIN ', 'PICAVIA', 'MEJIA', '483903 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (235, 'CEVERINO ', 'HILARIO', 'AREGON', '2160065 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (236, 'ENRY NELSON', 'ESTRADA', 'CARVAJAL', '2317334 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (237, 'MEDGAR ', 'BONIFACIO', 'MAMANI', '4206468');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (238, 'JACOB ', 'CHAVARRIA', 'CHUQUIMIA', '339767 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (239, 'MARCELINO ', 'FLORES', 'QUISPE', '2796911 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (240, 'DAMIAN ', 'HILARIO', 'MAMANI', '8433993 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (241, 'NEMECIO ', 'HILARIO', 'AREGON', '2244997 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (242, 'ANA ', 'JIMENEZ', 'DE FERNANDEZ', '3899498 SC.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (243, 'SABINA ', 'COARITE', 'NINA', '3404745 L.P');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (244, 'VICTOR HUGO', 'CONDORI', NULL, '65');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (245, 'MAVEL ', 'MARIELA', 'DURAN', '6873616 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (246, 'AMERICO ', 'VALDEZ', 'PICAVIA', '7796467 S.C.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (247, 'FLORA ', 'CHOQUE', 'MORALES', '4853692 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (248, 'ARMINDA ', 'FERNANDEZ', 'ORIHUELA', '9912331 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (249, 'RAMIRO ', 'MACHICADO', 'ARGOLLO', '6116640 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (250, 'BERNAL MELANIO', 'ESPINOZA', 'AGUILAR', '4782593 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (251, 'MARCO ANTONIO', 'FLORES', 'PLATA', '9929060 QR');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (252, 'ROSA ', 'HUANCA', 'DURAN', '3516596 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (253, 'MARIA RAQUEL', 'HUANCA', 'DURAN', '5196062 CB.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (254, 'JOSE ', 'VILLANUEVA', 'VALDEZ', '6997067 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (255, 'RAIMUNDO ', 'HILARIO', 'FERNANDEZ', '6997041 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (256, 'TORIBIO ', 'HILARIO', 'AREGON', '64');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (257, 'SAMUEL ', 'HILARIO', 'AREGON', '63');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (258, 'TEOFILO ', 'BALTAZAR', 'RAMIREZ', '2136195 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (259, 'ROBERTO ', 'HILARIO', 'SUMINA', '62');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (260, 'GUILLERMO ', 'SILES', 'JIMENEZ', '70874 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (261, 'AURORA ', 'FERNANDEZ', 'ORIHUELA', '61');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (262, 'MARIA REYNA', 'HILARIO', 'CORDOVA', '6999507 QR');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (263, 'observado ', 'AREA', 'VERDE', '60');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (264, 'SABINA ', 'COARITE', 'NINA', '3404745 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (265, 'NATIVIDAD ', 'GOMEZ', 'ALVAREZ', '2346057 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (266, 'TELESFORO ', 'ESPINOSA', 'LACOA', '9912838 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (267, 'IGLESIA ADVENTISTA', 'DEL SEPTIMO DIA CIRCUATA', NULL, '59');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (268, 'HUMBERTO ', NULL, NULL, '58');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (269, 'SABINO ', 'ORELLANA', 'HUAYNOCA', '9100471 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (270, 'JOSE ', 'PEREA', 'LACOA', '279408 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (271, 'MARTHA ', 'MAMANI', 'CHAMBI DE CHECA', '621099 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (272, 'MODULO POLICIAL', NULL, NULL, '57');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (273, 'JUANA ', 'MAMANI', 'LACOA', '2245013 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (274, 'BENJAMIN ', 'LIMA', 'FERNANDEZ', '7376620 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (275, 'JUSTO ', 'COCA', 'NAVIA', '2136975 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (276, 'MATEO ', 'ILARIO', 'MAMANI', '3301921 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (277, 'RIGOBERTO ', 'MURIEL', 'MOLINA', '3317152 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (278, 'JULIO ', 'APAZA', 'QUISPE', '3544868 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (279, 'FRANCISCO ', 'MAURIEL', 'MIRANDA', '3318170 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (280, 'ERCILIO ', 'QUISPE', 'AGUILAR', '7334055 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (281, 'ROSARIO ', 'MIRANDA', 'SOLARES', '6124232 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (282, 'SONILDA ', 'MIRANDA', 'SOLARES', '4809301 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (283, 'MARISOL ', 'MIRANDA', 'SOLARES', '4795193 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (284, 'GENARO ', 'LIMA', 'CALLE', '3051176 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (285, 'FELIZA ', 'CALAMANI', 'DE ESPINOZA', '2136999 -');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (286, 'VITALIA GARCIA', 'MAMANI', 'APAZA', '3509305 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (287, 'TEOFILO SATURNINO', 'CHOQUE', 'FERNANDEZ', '9114793 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (288, 'KAREN ', 'PAZ', 'GOMEZ', '5956804 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (289, 'LAURIANA ', 'CRUZ', 'AMARU DE MARIBAL', '3074203 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (290, 'PEDRO JUAN', 'MIRABAL', 'CRUZ', '7276151 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (291, 'MIRADOR ', NULL, NULL, '56');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (292, 'IGLESIA DE', 'DIOS', 'REFORMADA', '55');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (293, 'VITMAN ', 'BERRIOS', 'FLORES', '6120684 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (294, 'TEODORA ', 'CRUZ', 'CRISPIN', '3419195 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (295, 'GERMAN ', 'FIGUEROA', 'PICABIA', '2067977 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (296, 'ANGEL ', 'MAURIEL', 'MIRANDA', '2244851 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (297, 'RITA ', 'MAURIEL', 'MIRANDA', '2248096 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (298, 'ANTONIO VIDAL', 'DURAN', 'SOLARES', '9867538 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (299, 'CEMENTERIO GENERAL', 'CIRCUATA', NULL, '54');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (300, 'IGLESIA LAS', 'ASAMBLEAS', 'DE DIOS', '53');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (301, 'ARIEL MAURICIO', 'PICAVIA', 'BOLIVAR', '52');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (302, 'MARIA ELENA', 'BARRETO', 'CALLIZAYA', '6850831 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (303, 'IGLESIA ASAMBLEA', 'DE DIOS.', NULL, '51');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (304, 'FLORA ', 'ALI', 'MAMANI', '2244942 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (305, 'VILMA MALENA', 'GODOY', 'CHACON', '8417866');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (306, 'ALBERTINA ', 'APAZA', 'SARZURI DE MAMANI', '7410088 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (307, 'MATEO ', 'MAMANI', 'MAMANI', '483814 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (308, 'TOMASA ', 'LUPINTA', 'PALMA', '5307103 CB.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (309, 'ZENON ', 'GUILLEN', 'NAVIA', '865826 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (310, 'ERNESTO ', 'CONDORI', 'MARCA', '9179626 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (311, 'DELFINA ', 'PICAVIA', 'COSSIO', '9717484 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (312, 'JUNTA DE', 'VECINOS', NULL, '50');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (313, 'RODOLFO ', 'LIMA', 'LAURA', '9912327 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (314, 'TITO ', 'ESPINOZA', 'FERNANDEZ', '8361577 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (315, 'ALEJANDRA ', 'PATIÑO', 'ROMERO', '3508769 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (316, 'NORMA ESPINOZA', 'DE', 'CRUZ', '4322090 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (317, 'ROBERTO ', 'QUINO', 'ALVAREZ', '2329481 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (318, 'FATIMA ', 'QUINO', 'DURAN', '6241595 SC.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (319, 'VICENTE ', 'AGUIRRE', 'ULLOA', '2136886 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (320, 'DONATO ', 'MEJIA', 'COSSIO', '9184784 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (321, 'FLORENCIO ', 'LIMA', 'LAURA', '9912601 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (322, 'ELIA ', 'QUISPE', 'INCA', '5990126 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (323, 'FELIPE ', 'GOMEZ', 'MAMANI', '2148369 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (324, 'FELIX ', 'AREGON', 'ZARZURI', '9911555 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (325, 'MOISES MANUEL', 'FLORES', 'SANTOS', '9060783 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (326, 'FILOMENA ', 'MORALES', 'NABARRO', '3318146 L.P');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (327, 'FILOMENA ', 'MORALES', 'NABARRO', '3318146');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (328, 'RUDDY VIDAL', 'OLIVER', 'MORALES', '6999434 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (329, 'AMERICO ', 'VALDEZ', 'PICAVIA', '7793437 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (330, 'JONATAN ', 'LLAVE', 'BARRETO', '9060606 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (331, 'FELIPA ', 'COCA', 'VEIZAGA', '6997059 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (332, 'MIGUEL ANGEL', 'AYAVIRI', 'SOLARES', '9060560 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (333, ' BENJAMIN', 'LIMA', 'FERNANDEZ', '7376620 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (334, 'DAMIAN ', 'CALDERON', 'MORALES', '483851 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (335, 'SANDRA ', 'ESPINOZA', 'PATINO', '8436091 LP');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (336, 'MARIA ', 'JULIA', 'PATINO', '5962201 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (337, 'SABINA ', 'HILARIO', 'MAMANI', '6999416 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (338, 'MARIO ', 'HUARACHI', 'FLORES', '2797177 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (339, 'SILVIA ', 'PATINO', 'COCA', '9060719 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (340, 'CRISTOBAL ', 'PATINO', 'ROMERO', '2796914 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (341, 'SANTIAGO ', 'PATINO', 'COCA', '6924709 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (342, 'SANDRO ', 'AGUIRRE', 'PEREZ', '6206895 SC.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (343, 'ROSMERY ', 'AGUIRRE', 'PEREZ', '4773993 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (344, 'PORFIRIA ROSMERY', 'MOYA', 'MAMANI', '13380864 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (345, 'OLGA ', 'ESTRADA', NULL, '9912276 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (346, 'SILVIA CAROLINA', 'PEREZ', 'ESTRADA', '6797765 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (347, 'GERARDO ', 'AGUIRRE', 'PEREZ', '4290004 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (348, 'NERFILIA ', 'PEREZ', 'ESPINOZA', '2136825 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (349, 'HEBERTH ', 'SALCEDO', 'ALAVI', '6457912 CB.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (350, 'DAVID ', 'CALAMANI', 'NINA', '6184087 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (351, 'MARIA ROXANA', 'FERNANDEZ', 'PACO', '9910561 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (352, 'AREA VERDE', NULL, NULL, '49');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (353, 'MARIO ', 'ARUQUIPA', 'COSSIO', '6152103 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (354, 'MIRIAM ', 'BELLIDO', 'COSSIO', '4827651 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (355, 'MANUEL ALEJANDRO', 'VALDEZ', 'PACHECO', '8394725 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (356, 'ANGEL GABRIEL', 'PICAVIA', 'BONIFACIO', '9060531 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (357, 'MIRIAM ', 'ALANOCA', 'PANI', '48');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (358, 'JOSE CUPERTINO', 'HILARIO', 'FLORES', '3548300 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (359, 'JUNTA DE', 'VECINOS', '.', '47');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (360, 'FRANKLIN MICHAEL', 'MEJIA', 'CALAMANI', '6905053 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (361, 'CARMEN ROSA', 'ARGOLLO', 'CONDORI', '9911551 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (362, 'YESVER ', 'LAURA', 'CAMARA', '8365062 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (363, 'EDWIN ', 'MIRANDA', 'SOLARES', '4791519 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (364, 'EVA ', 'BLAZ', 'JAILLITA', '7923097 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (365, 'NICOLAS ', 'PALMA', 'APAZA', '2437291 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (366, 'JULIAN ', 'CHOQUE', 'LIMACHI', '2241802 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (367, 'JUANA ', 'HUANTO', 'HILARIO DE FERNANDEZ', '6097242 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (368, 'MARIO ', 'COCA', 'LOZA', '9413687 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (369, 'PILAR ', 'COCA', 'LOZA', '4738893 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (370, 'ZENOBIA ', 'BOYAN', 'ONOSTRE', '2677551 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (371, 'CARMEN ADELA', 'COCA', 'VEIZAGA', '9912290 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (372, 'GIOVANI ', 'LAURA', 'CAMARA', '8361384 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (373, 'CASILDA ', 'BOYAN', 'ONOSTRE', '3406451 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (374, 'WINSOR ', 'BOYAN', 'ONOSTRE', '4792649 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (375, 'GERMAN JAVIER', 'BOYAN', 'ONOSTRE', '4752799 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (376, 'ADA MELISSA', 'BOYAN', 'ONOSTRE', '6889629 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (377, 'PARQUE MIRADOR', 'CIRCUATA', '2', '46');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (378, 'ELSA ', 'SEGOVIA', 'MENCIA', '3408084 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (379, 'EDWIN BENJAMIN', 'CALAMANI', 'NINA', '6721394 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (380, 'VICTORIA ', 'ILARIO', 'ARUQUIPA', '9060725 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (381, 'GUALBERTO ', 'CHAMBI', 'CABEZAS', '2136896 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (382, 'MIGUEL ANGEL', 'CHAMBI', 'PEREA', '5972824 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (383, 'SANTIAGO ', 'HILARIO', 'MAMANI', '6997065 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (384, 'AREA DE', 'EQUIPAMIENTO', NULL, '45');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (385, 'NATIVIDAD ', 'FLORES', 'ROMUALDO', '5138743 PT.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (386, 'SILVIA ', 'GUTIERREZ', 'ZAMORA', '9060505 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (387, 'TANQUE DE AGUA', 'POTABLE', 'CIRCUATA', '44');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (388, 'LIZANDRO ', 'QUIROGA', 'MANZANO', '6999414 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (389, 'PLACIDA ', 'FLORES', 'ROMUALDO DE COSME', '10504509 PT.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (390, 'RAMIRO ', 'TANGORA', 'GUTIERREZ', '3109421 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (391, 'SEBASTIAN ', 'QUISPE', 'MAMANI', '3660404 PT.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (392, 'EPIFANIO ', 'CALLE', 'COCA', '2176747 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (393, 'FRANKLIN ', 'CALLE', 'CADENA', '6997080 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (394, 'LIDIA ', 'PARI', 'QUISPE', '9912257 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (395, 'JUNTA DE', 'VECINOS', NULL, '43');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (396, 'JUNTA DE', 'VECINOS', NULL, '42');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (397, 'ERICA GABRIELA', 'CHAMBI', 'PEREA', '6866358 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (398, 'DORCAS MARIBEL', 'CHAMBI', 'PEREA', '4852107 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (399, 'RAQUEL VERONICA', 'CHAMBI', 'PEREA', '4770812 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (400, 'SONIA ', 'CALLE', 'CADENA', '6757713 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (401, 'CARMELO ', 'PAILL0', 'MITMA', '2768994 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (402, 'DAYSI KAREN', 'MAMANI', 'COARITE', '8291312 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (403, 'MIGUEL ', 'MORALES', 'IPORRE', '6750619 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (404, 'MARIN ', 'LAURA', 'MAMANI', '10040503 LP');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (405, 'CARLOS ABDON', 'QUISPE', 'ZUAREZ', '4217166 PD.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (406, 'LUCIA MAMANI', 'MONTALVO', NULL, '12807196 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (407, 'WINSOR GILSON', 'PICAVIA', 'ENRRIQUEZ', '9912171 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (408, 'GONZALO ', 'JIMENEZ', NULL, '5353682 SC.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (409, 'ROLANDO ', 'COCA', 'LOZA', '9060739 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (410, 'JUSTA ', 'COCA', 'LOZA', '6755042 LP');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (411, 'LUIS ', 'ILARIO', 'ARUQUIPA', '9060724 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (412, 'TEODOMIRO ', 'CHOQUE', 'FERNANDEZ', '6091950 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (413, 'FRANKLIN ', 'SOLARES', 'LOPEZ', '6789949 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (414, 'FLORENCIO ', 'LIMA', 'LAURA', '9912601 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (415, 'BETHZAIDA ', 'ILARIO', 'ARUQUIPA', '9060726 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (416, 'VICTORIA ', 'ILARIO', 'ARUQUIPA', '9060725 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (417, 'PLAZA EL', 'PARAISO', NULL, '41');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (418, 'DEMETRIO ', 'ALANOCA', 'PANI', '9060802 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (419, 'AURORA ', 'SOLARES', 'DE MIRANDA', '2522695 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (420, 'GILARY MELL', 'RUEDA', 'MARCA', '6999458 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (421, 'GILARY MELL', 'RUEDA', 'MARCA', '6999458 LP');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (422, 'ANGEL ', 'PICAVIA', NULL, '2796999 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (423, 'HERLAN ', 'PICAVIA', 'BONIFACIO', '9060736 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (424, 'JUNTA DE', 'VECINOS', NULL, '40');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (425, 'JUNTA DE', 'VECINOS', NULL, '39');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (426, 'ESCUELA PRIMARIA', NULL, NULL, '38');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (427, 'ZULMA ', 'PINEDO', 'PEÑA', '9052783 S.C.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (428, 'JAQUELINE ', 'PEREA', 'MIRANDA', '3441541 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (429, 'CRISTINA ', 'MIRANDA', NULL, '2245106 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (430, 'RENE FRANCISCO', 'SACA', 'MOYA', '2392110 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (431, 'PEDRO ', 'MAMANI', 'TERRAZAS', '2796905 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (432, 'AREA DE', 'EQUIPAMIENTO', NULL, '37');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (433, 'RENE ', 'CHOQUE', 'GUIZADA', '2136930 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (434, 'FRUCTUOSO ', 'LAURA', 'MEJIA', '2796983 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (435, 'ARMANDO ', 'PEREA', 'LACOA', '656672 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (436, 'RIONET ', 'MEJIA', 'CALATAYUD', '6999417 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (437, 'NOLBERTO ', 'CORANI', 'NAVIA', '9244680 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (438, 'MARIO ', 'HUARACHI', 'FLORES', '2797199 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (439, 'RENE ', 'OLIVER', 'ROJAS', '2618641 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (440, 'HERNAN ', 'CAMPOSALADO', 'HUARACHI', '4894698 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (441, 'ROLANDO ', 'FERNANDEZ', 'DE FERNANDEZ', '6977822 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (442, 'EDMUNDO CARLOS', 'CALLEJAS', 'VELASCO', '2136888 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (443, 'MARIA RAQUEL', 'HUANCA', 'DURAN', '5196062 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (444, 'GISELA MISCHEL', 'ESTRADA', 'HUANCA', '10095598 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (445, 'HERIBERTO ELOY', 'PICAVIA', 'BOLIVAR', '4626394 SC.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (446, 'ROCY DELIA', 'FUENTES', 'RAMIREZ', '9899605 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (447, 'BETTY MARIA', 'GUTIERREZ', 'ZAMORA', '6997045 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (448, 'LUIS HANCEL', 'MENA', 'AGUILAR', '6760212 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (449, 'ANIBAL ', 'BUSTOS', 'RODRIGUEZ', '3510755 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (450, 'MAXIMA ', 'LACOA', 'VDA. DE ZURITA', '6080075 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (451, 'VICTOR ', 'INCA', 'CASERES', '4267086 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (452, 'ERMINIO ', 'AGUIRRE', 'MIRANDA', '6091945 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (453, 'RUTH EVELYN', 'HUANCA', 'DAVILA DE AGUIRRE', '4844821 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (454, 'JUAN CARLOS', 'CALLEJAS', 'RODRIGUEZ', '5431630 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (455, 'ADELAIDA ', 'LEON', 'DE GUTIERREZ', '2202617 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (456, 'ARMINDA ', 'LEON', 'RODRIGUEZ', '2244856 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (457, 'ALEJANDRO ', 'QUITO', 'ZAPATA', '3913519 SC.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (458, 'JUAN ', 'QUITO', 'ZAPATA', '3526563 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (459, 'MATILDE ', 'MENA', 'DE MEJIA', '6763981 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (460, 'CENTRO DE', 'SALUD', NULL, '36');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (461, 'AGUSTINA ', 'CALATAYUD', 'DE MEJIA', '2244867 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (462, 'HILARION ', 'MUNOZ', 'LOPEZ', '9912759 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (463, 'CELESTINA ', 'RODRIGUEZ', NULL, '456102 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (464, 'FELIPE ', 'MUNOZ', 'LOPEZ', '4268605 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (465, 'MARIO ', 'URUNA', 'MALLCU', '2136853 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (466, 'TEODORO ', 'SOLARES', 'MUNOZ', '35');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (467, 'RENE ', 'MEJIA', 'CALATAYUD', '2182314-1Q LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (468, 'CLARA ', 'MUNOZ', 'LOPEZ', '2136985-1R LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (469, 'JULIA ', 'ALBA', 'CONDORI', '3474225 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (470, 'JAVIER ', 'PICABIA', NULL, '5948152 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (471, 'GABRIEL HIPOLITO', 'VILLANUEVA', 'HILARIO', '7017737 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (472, 'LUCIO SANTOS', 'HILARIO', 'FLORES', '6999410 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (473, 'EDUARDO WALDO', 'HILARIO', 'FLORES', '7906573 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (474, 'ADRIANA ', 'SANSUSTE', NULL, '6999406 LP');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (475, 'SIN NOMBRE', NULL, NULL, '34');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (476, 'BERTA ', 'FELIPE', 'VALENCIA', '9912717 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (477, 'RODOLFO ', 'URUNA', 'MORALES', '9912842 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (478, 'ARMANDO ', 'ENRIQUEZ', 'CARDOZO', '6773495 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (479, 'JOSE LUIS', 'JIMENEZ', 'VELASQUEZ', '3300551 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (480, 'JUVENAL ', 'BAUTISTA', 'PAZ', '13158319 QR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (481, 'ANGEL ', 'LUPINTA', 'PALMA', '6999401 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (482, 'EDY ', 'URUÃ‘A', 'SOLARES', '4909167 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (483, 'BIANCA NIVES', 'EGUINO', 'DURAN', '8365368 L.P');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (484, 'ISELA NANCY', 'FERNANDEZ', 'SILES', '4292247 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (485, 'BENZU TIMOTEO', 'RAMIREZ', 'VALLEJOS', '6158938 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (486, 'AMERICO ', 'VALDEZ', 'PICAVIA', '7793437 SC.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (487, 'GRIZELDO ', 'MERLO', 'CORDERO', '3308094 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (488, 'ALFREDO ', 'ESTRADA', 'FERNANDEZ', '6091936 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (489, 'CELESTINO ', 'MEJIA', 'MENA', '9912784 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (490, 'LUIS ALBERTO', 'PEREZ', 'ALAVE', '8826621 CB.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (491, 'ESTANISLAO COSIO', NULL, NULL, '33');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (492, 'JOSE GABRIEL', 'ESCOBAR', 'PINTO', '2756972 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (493, 'JAVIER ', 'FERNANDEZ', 'SILES', '2248118 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (494, 'JOSUE GERSON', 'FERNANDEZ', 'TICONA', '8328743 L.P');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (495, 'MARILU BETTY', 'FERNANDEZ', 'SILES', '3465181 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (496, 'IVAN ', 'LAURA', 'NAVIA', '6770830 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (497, 'GRECIA SELENA', 'PACHECO', 'ARZA', '9060607 QR');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (498, 'CARLOS MIGUEL', 'CALAMANI', 'NINA', '6721649 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (499, 'ANGEL ', 'PEREZ', 'ESTRADA', '4913271');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (500, 'LIDIA ', 'PARI', 'QUISPE DE GUTIERREZ', '9912257');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (501, 'ARMIN ', 'COSSIO', 'LOZA', '8425863 L.P');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (502, 'OLGA VERONICA', 'URUÃ‘A', 'SOLARES', '6137103 L.P');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (503, 'ZENOBIO ', 'PICAVIA', 'MEJIA', '483941 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (504, 'PARQUE MIRADOR', 'CIRCUATA', '1', '1');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (505, 'EYID ', 'PEREZ', 'CARDENAS', '2796858 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (506, 'EDGAR ', 'PEREZ', 'CARDENAS', '6808954 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (507, 'GENIO ', 'PEREZ', 'CARDENAS', '3475204 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (508, 'JOSE ANGEL', 'PEREZ', 'CARDENAS', '4779443 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (509, 'INGRITT ', 'PEREZ', 'CARDENAS', '4742196 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (510, 'HUGO ', 'MIRANDA', 'VEIZAGA', '3746382 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (511, 'ANGEL ', 'PEREZ', 'ESTRADA', '13380864 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (512, 'POLIFUNCIONAL ', NULL, NULL, '32');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (513, 'AREA DE', 'EQUIPAMIENTO', NULL, '31');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (514, 'SANTOS LINO', 'MAMANI', 'HILARIO', '9060785 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (515, 'RICARDO BENITO', 'RAMIREZ', 'CALLIZAYA', '4063452 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (516, 'ELIZABET ', 'FERNANDEZ', 'SILES', '3049865 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (517, 'ROSA ', 'RAMIREZ', 'VALLEJOS', '2796903 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (518, 'GONZALO ', 'FLORES', 'MAMANI', '5301031 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (519, 'IGIDIO ', 'HUANCA', 'PADILLA', '3411297 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (520, 'BENIGNA ', 'RUEDA', 'MARCA', '8342131 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (521, 'JUVENAL ', 'TORREZ', 'CORANI', '8729489 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (522, 'ABDON ', 'NAVIA', 'FERNADEZ', '8432942 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (523, 'ABDON ', 'NAVIA', 'FERNANDEZ', '8432942 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (524, 'EDUARDO WALDO', 'HILARIO', 'FLORES', '7906573 CB.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (525, 'CARLOS ', 'CALATAYUD', 'MERCADO', '2136904 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (526, 'ALEJANDRA ', 'SIPE', 'DE MORALES', '7292254 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (527, 'PONCIANO ', 'RAMIREZ', 'ZURITA', '2245053 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (528, 'JOSEFINA ', 'RAMIREZ', 'VALLEJOS', '6757696 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (529, 'LIDIO ', 'HUANCA', 'DURAN', '6757722 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (530, 'JEANS TINITO', 'AGUIRRE', 'INCA', '6803873 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (531, 'JESENIA BRISICHS', 'VALVERDE', 'BOYAN', '9912843 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (532, 'EDIL EDWIN', 'VALDEZ', 'AGUILAR', '3382936 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (533, 'GELLY CAROLINA', 'VALDEZ', 'AGUILAR', '4748280 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (534, 'JEANNET TERESA', 'VALDEZ', 'AGUILAR', '6785636 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (535, 'GEMA LUDY', 'VALDEZ', 'AGUILAR', '3380673 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (536, 'GROBER IVAN', 'VALDEZ', 'AGUILAR', '4244428 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (537, 'BLADIMIR OSWALD', 'VALDEZ', 'AGUILAR', '4868122 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (538, 'MARTHA ALEJO', 'TORREZ', 'CATARI', '3553788 OR');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (539, 'JUAN CARLOS', 'TANGORA', 'APAZA', '6817798 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (540, 'MARTHA ', 'ALEJO', 'TORREZ DE CATARI', '3553788 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (541, 'NAZARIA ', 'LOPEZ', 'MAMANI', '2182312 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (542, 'EDY ', 'URUNA', 'SOLARES', '4909167 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (543, 'ROGER MARIO', 'MORALES', 'CARDOZO', '9061052 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (544, 'FLORENCIO ', 'ALEJO', 'ROQUE', '616407 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (545, 'ROSENDO ', 'APAZA', 'QUISPE', '5248041 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (546, 'JUNTA DE', 'VECINOS', NULL, '30');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (547, 'JOSE ', 'CONDORI', 'HUANCA', '2263317 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (548, 'ABDON ', 'NAVIA', 'FERNANDEZ', '8432942 LP');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (549, 'JUANA ', 'DURAN', 'DE HUANCA', '5973003 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (550, 'ANIBAR ', 'SOLARES', 'LOPEZ', '9912245 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (551, 'DIONICIO ', 'NAVIA', 'NABARRO', '2492421 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (552, 'REYNA ', 'VARGAS', 'VALENCIA', '9912811 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (553, 'SEVERINA ', 'SOLARES', 'MUÃ‘OZ', '9060809 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (554, 'FRANZ ', 'CAMPOS', 'BOYAN', '459302 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (555, 'SENON AGAPITO', 'MUNOZ', 'PACHETO', '7879428 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (556, 'SANTIAGO ', 'NAVIA', 'NAVARRO', '9912273 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (557, 'DAVID ', 'FLORES', 'SANTOS', '9060610 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (558, 'LUIS ', 'MOLLO', 'TAPIA', '6127192 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (559, 'TEODORO ', 'NAVIA', 'FERNANDEZ', '9912195 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (560, 'ZENON ', 'COSSIO', 'CHOQUE', '865851 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (561, 'MARIA ', 'COSSIO', 'MAMANI', '8731341 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (562, 'GREGORIA ', 'NAVIA', 'FERNANDEZ', '9912325 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (563, 'EDWIN ', 'ARGOLLO', 'CONDORI', '9912161 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (564, 'RIGOBERTO ', 'MORALES', 'ZEGARRA', '2182333 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (565, 'ARIANA AMALIA', 'ARRATIVA', 'VARGAS', '6876676 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (566, 'OCTAVIO ', 'MAMANI', 'TORREZ', '6770889 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (567, 'DIONY ', 'SOLARES', 'LOPEZ', '9912807 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (568, 'GILSON ', 'CALAMANI', 'HILARIO', '7300361 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (569, 'MAX JUAN', 'SOLARES', 'LOPEZ', '5960616 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (570, 'VIKI REYNI', 'VILLAR', 'CARDENAS', '9912737 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (571, 'FERNANDO ', 'VILLAR', 'CARDENAS', '29');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (572, 'ALISON ', 'JIMENEZ', 'VILLAR', '28');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (573, 'SAUL WASKAR', 'JIMENEZ', 'VILLAR', '27');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (574, 'JESUS ALEXANDER', 'JIMENEZ', 'VILLAR', '26');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (575, 'MARIO DELFIN', 'VILLAR', 'CARDENAS', '4199929 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (576, 'ELIAS ', 'ZURITA', 'LACOA', '2299987 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (577, 'RILDO ELOY', 'TORRELIO', 'PICAVIA', '6955206 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (578, 'MAXIMA ', 'NAVIA', 'NAVARRO DE MUNOZ', '7282883 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (579, 'FRANCISCO ', 'NAVIA', 'BERNAVE', '7888054 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (580, 'OCTAVIA ', 'CONDORI', 'HUAYNOCA DE ARGOLLO', '6130060 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (581, 'RICARDO RICHART', 'PICAVIA', 'ENRRIQUEZ', '9060746 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (582, 'ESTANISLAO ', 'COSSIO', 'LOZA.', '25');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (583, 'ISRRAEL ', 'CALAMANI', 'NINA', '-6941496 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (584, 'ISMAEL TOMAS', 'HUANCA', 'DURAN', '6999420 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (585, 'AREA VERDE', 'OJO', NULL, '24');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (586, 'FRUCTUOSO ', 'LAURA', 'MEJIA', '2796983 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (587, 'LEONEL ', 'GUTIERREZ', 'MAMANI', '6116637 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (588, 'GERARDO ', 'MUNOZ', 'PACHECO DE MUNOZ', '7261646 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (589, 'NELLYDA ', 'MUNOZ', 'NAVIA', '6999454 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (590, 'JUNTA DE', 'VECINOS', NULL, '23');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (591, 'ORLANDO ', 'MAMANI', 'QUISPE', '9912170 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (592, 'PAPIAS MAURO', 'MAMANI', 'SUMI', '4844247 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (593, 'MARIA LUISA', 'NAVARRO', 'RUEDA', '4040819 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (594, 'GUIDO ', 'NAVARRO', 'RUEDA', '12829330 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (595, 'LEICY MANNETH', 'MORALES', 'GUTIERREZ', '9385383 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (596, 'REMIGIO ', 'NAVIA', 'NAVARRO', '6999428 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (597, 'RAFAEL ', 'MORALES', 'CAVEZAS', '5060609 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (598, 'DELIA ', 'AGUIRRE', 'MERCADO', '9912837 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (599, 'EVANGELINA ', 'MAMANI', 'TERRAZAS', '8731397 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (600, 'ESIQUEL ', 'MAMANI', 'TERRAZAS', '9891586 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (601, 'MADELIN MELANIA', 'MAMANI', 'COSSIO', '5991591 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (602, 'MARCELINO ', 'LUPINTA', 'PALMA', '13062870 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (603, 'RIQUEL ', 'LOZA', 'LUPINTA', '6438689 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (604, 'HECTOR ', 'CONDORI', 'MAMANI', '2796960 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (605, 'ERMINIA MAGDALENA', 'CONDORI', 'COLQUE', '5990231 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (606, 'MARCIAL CASTO', 'FLORES', 'CONDORI', '4940454 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (607, 'EVER ', 'QUISPE', 'MAMANI', '9060595 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (608, 'LOLA ', 'PATRICIA', 'RODRIGUEZ', '2248100 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (609, 'SULMA ', 'SEGOBIA', 'MENCIA', '6870990 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (610, 'BLADIMIR ', 'PEREZ', 'MEJIA', '6999452 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (611, 'JUAN ', 'NAVIA', 'NAVARRO', '6999408 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (612, 'LUIS FROILAN', 'QUISPE', 'TAPIA', '6126003 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (613, 'CESAR ANGEL', 'MAMANI', 'COSSIO', '6120718 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (614, 'GABINO ', 'GUTIERREZ', 'CRUZ', '5159506 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (615, 'JUANA ', 'ATANACIO', 'AGUILAR', '631036 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (616, 'DEMETRIO ', 'ENRRIQUEZ', 'GUILLEN', '261029 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (617, 'RAMIRO FELIPE', 'NAVIA', 'MUNOZ', '9060771 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (618, 'EUGENIO ', 'NAVIA', 'CORANI', '865927 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (619, 'HURVANO ', 'NAVIA', 'MUNOZ', '4496267 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (620, 'EVELINA ', 'GUTIERRES', NULL, '5213210 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (621, 'APOLINAR DAVID', 'MAMANI', 'COSSIO', '9061124 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (622, 'EUSEBIO ', 'QUISPE', 'PORTO', '483940 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (623, 'CANCHA DE', 'FUTBOL', NULL, '22');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (624, 'COLEGIO CIRCUATA  II', NULL, NULL, '21');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (625, 'HERIBERTO ', 'ENRIQUEZ', 'CARDOZO', '3438488 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (626, 'LIDIA ', 'MEJIA', NULL, '6999445 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (627, 'ROGELIA ', 'ENRIQUEZ', 'CARDOZO', '2375819 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (628, 'TERSO ', 'EGUINO', 'DURAN', '20');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (629, 'ARMIN WILLIAM', 'MIRANDA', 'NAVIA', '7732249 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (630, 'ROSALBA ', 'ROSMERY', 'SILES DE CASTRO', '3598864 CB.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (631, 'JUNTA DE', 'VECINOS', NULL, '19');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (632, 'SANDRA NINOSCA', 'SILES', 'MERCADO', '5990183 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (633, 'LIMBER RONAL', 'MAMANI', 'QUISPE', '6997078 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (634, 'JACOB ', 'CALAMANI', 'NINA', '6999441 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (635, 'ROY ', 'QUISPE', 'MAMANI', '6999466 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (636, 'HENRY ', 'MAMANI', 'SUMI', '4910566 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (637, 'EDWIN ', 'ANDRADE', 'VILLANUEVA', '3072391 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (638, 'NORAH ', 'KALLY', 'JAVIER', '5634307 CHS.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (639, 'DELIA ', 'PEREA', 'COCA', '6997058 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (640, 'DEMETRIO ', 'ALANOCA', 'PANI', '9060802 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (641, 'BENIGNO ', 'VILLEGAS', 'LOZA', '6091919 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (642, 'BLADIMIR ', 'MAMANI', 'SANTOS', '6954891 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (643, 'MAXIMO ', 'HILARIO', 'MAMANI', '6997068 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (644, 'SINTIA ', 'HUANCA', 'DURAN', '6952396 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (645, 'LILIAN ', 'CALLIZAYA', 'MEDINA', '9060921 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (646, 'FERMIN ', 'ARROYO', 'MUNOZ', '9060559 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (647, 'VICTOR BENITO', 'MAMANI', 'COSSIO', '18');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (648, 'GREGORIO ', 'TORRELIO', 'MOLLINEDO', '643442 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (649, 'MERCEDES YAZMIN', 'PACHECO', 'ARZA', '8341047 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (650, 'KATHERINE YESENIA', 'PACHECO', 'ARZA', '4793657 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (651, 'FERNANDO DAVID', 'PACHECO', 'ARZA', '4775169 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (652, 'FELIX ', 'CALAMANI', 'NINA', '9881950 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (653, 'TERESA ', 'HILARIO', 'AREGON', '2695523 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (654, 'EDDITH ', 'ESTRADA', 'FERNANDEZ', '6754376 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (655, 'ZAIDA ', 'GUIZADA', 'ARDAYA', '6999440 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (656, 'AREA VERDE', NULL, NULL, '17');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (657, 'CARLA ROCIO', 'CHACON', 'VARGAS', '9060613 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (658, 'IVETH ', 'CHACON', 'VARGAS', '9060619 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (659, 'MARTHA ', 'CONDORI', 'MAMANI', '2248140 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (660, 'CESAR ', 'QUISPE', 'MAMANI', '9060615 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (661, 'ANA MAVEL', 'LAURA', 'AYAVIRI', '7267370 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (662, 'WIELDER ', 'RUEDA', 'MARCA', '7263364 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (663, 'JOSE LUIS', 'MAMANI', 'QUISPE', '6997077 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (664, 'VITALIO ', 'FERNADEZ', NULL, '16');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (665, 'PABLO CHAMBI', 'MARCA', NULL, '9060778 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (666, 'CANDELARIA NELI', 'CALAMANI', 'NINA', '5977635 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (667, 'JHEFERSON ', 'AGUIRRE', 'MORALES', '9910558 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (668, 'CARLA ROCIO', 'CHACON', 'VARGAS', '9060613 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (669, 'CANDELARIA ', 'CALLEJAS', 'SULLCANI', '3787548 CB.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (670, 'HUMBERTO ', 'HUANCA', 'DURAN', '3334780 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (671, 'SEGUNDINA ', 'CHAMBI', 'VICENTE', '10089290 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (672, 'MOISES ', 'ALANOCA', 'PANI', '9060803 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (673, 'AREA DE', 'EQUIPAMIENTO', 'VIVERO', '15');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (674, 'EDGAR ', 'BALTAZAR', 'TANCARA', '12492676 QR');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (675, 'JUAN CARLOS', 'ARUQUIPA', 'COSSIO', '4901626 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (676, 'GONSY ', 'PACO', 'QUISPE', '6972410 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (677, 'ELID CLEOFE', 'ARUQUIPA', 'COSSIO', '9863393 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (678, 'ORLANDO ', 'COSSIO', 'MAMANI', '8002358 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (679, 'OVALDO ', 'NAVIA', 'CHAMBI', '9395416 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (680, 'NATALIA EMELINA', 'HILARIO', 'CORDOVA', '9060795 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (681, 'FLORIAN ', 'MAMANI', 'COSSIO', '6120717 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (682, 'JUAN MARCELO', 'AGUIRRE', 'VACA', '6091932 LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (683, 'COMPLEJO DEPORTIVO', NULL, NULL, '14');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (684, 'UNIVERSIDAD ', NULL, NULL, '13');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (685, ' PARQUE', 'MIRADOR', 'CIRCUATA', ' PARQUE');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (686, 'CRISTINA ', 'VALDEZ', 'OLIVERA', '4482666 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (687, 'ELIZA MARTHA', 'FERNANDEZ', 'ORIHUELA', '3509308 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (688, 'EDWIN ', 'BENJAMIN', 'CALAMANI', '6721394 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (689, 'CARLOS MIGUEL', 'CALAMANI', 'NINA', '6721649 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (690, 'ALFREDO ', 'ESTRADA', 'FERNANDEZ', '6091936 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (691, 'CRISTIAN ALDAIR', 'NAVIA', 'CARDENAS.', '8325396 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (692, 'JHOMARA TATIANA', 'NAVIA', 'CARDENAS', '8317663 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (693, 'ANGELA YOANDA', 'NAVIA', 'CARDENAS', '6868060 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (694, 'GONZALO JIMENEZ', NULL, NULL, '12');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (695, 'YHASCARA YUSETH', 'TANGORA', 'VARELA', '8359465 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (696, 'REYLAN BORIS', 'MORALES', 'LAURA', '8401980 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (697, 'ELSA LAURA', 'NAVIA', NULL, '11');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (698, 'MIGUEL ANGEL', 'MAMANI', 'COSSIO', '10');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (699, 'LEONEL ', 'GUTIERREZ', 'MAMANI', '6116637 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (700, 'RICHARD ', 'MALDONADO', 'MORALES', '4847506 L.P');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (701, 'CESAR ANGEL', 'MAMANI', 'COSSIO', '9');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (702, 'JUAN ', 'MORALES', NULL, '8');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (703, 'ARMANDO ', 'MORALES', 'COCA', '9060978 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (704, 'MIGUEL ANGEL', 'MIRANDA', 'PEREZ', '8305958 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (705, 'JOSE ANGEL', 'PEREZ', 'CARDENAS', '4779443 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (706, 'EDITH ', 'PEREZ', 'ESTRADA', '4829515 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (707, 'AMANDA ', 'PEREZ', 'ANDRADE', '8308299 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (708, 'GUSTAVO ', 'PEREZ', 'SALAZAR', '4786831 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (709, 'VICTOR ANGEL', 'PEREZ', 'SALAZAR', '6738662 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (710, 'JOSE ANGEL', 'PEREZ', 'CARDENAS', '4779443.L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (711, 'CORAIMA MIRANDA', 'PEREZ', NULL, '8394757 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (712, 'ENRY NELSON', 'ESTRADA', 'CARVAJAL', '2317334 L.P');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (713, 'ROGER MARIO', 'MORALES', 'CARDOSO', '9061052 QR');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (714, 'JULIAN ', 'MAMANI', 'GOMEZ', '4485942 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (715, 'DAVID ', 'CUBA', 'HUANCA', '13161254 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (716, 'LUZ NELLY', 'FLORES', 'HUANCA', '8394732 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (717, 'MARIO OCTAVIO', 'MIRANDA', 'NAVIA', '5769760 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (718, 'GUILBER ', 'MIRANDA', 'NAVIA', '7394510 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (719, 'VANIA ', 'MIRANDA', 'NAVIA', '5963515 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (720, 'RAMIRO CHOQUE', 'QUIROZ', 'MAMANI', '8700870 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (721, 'WALTER GUSTAVO', 'GUTIERREZ', 'MAMANI', '9060713 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (722, 'MARCO ANTONIO', 'NINA', 'ROCHA', '9060547 L.P..');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (723, 'EUSEBIA ', 'AGUIRRE', 'HUARACHI', '7');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (724, 'WILDER ', 'VASQUEZ', 'USCAMAYTA', '13377799 QR');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (725, 'GUADALUPE ', 'COCA', 'CALLE', '5985168 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (726, 'JOSUE JEDIDIAS', 'FORONDA', 'CRUZ', '9060513 QR');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (727, 'YENO ', 'MIRANDA', 'BOYAN', '2248086 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (728, 'JOSE VILLA', 'NUEVA', 'VALDEZ', '6997067 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (729, 'GROVER ROMULO', 'VILLANUEVA', 'HILARIO', '9912312 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (730, 'EVARISTO MARCELINO', 'FERNANDEZ', 'GUARAYA', '6116624 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (731, 'RAIMUNDO ', 'HILARIO', 'FERNANDEZ', '6997041 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (732, 'CLEOFE CASILDA', 'ARCANI', 'TANGORA', '9911550 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (733, 'TORIBIO ', 'HILARIO', 'AREGON', '483827 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (734, 'SIXTO', 'MUÃ‘OZ', NULL, '6');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (735, 'ROGELIO LIMACO', 'SIPE', 'FELIPE', '6999437 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (736, 'JUNTA DE', 'VECINOS', NULL, '5');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (737, 'GENARO ', 'MAMANI', 'PACO', '2131681 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (738, 'ROBERTA ', 'ARUQUIPA', 'COSSIO', '5616513 BN.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (739, 'ALFREDO ', 'HILARIO', 'CORDOVA', '9060622 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (740, 'SILVIA ', 'COCA', 'MEJIA', '6989799 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (741, 'ADRIAN DAMASO', 'TINCUTA', 'MAMANI', '9093159 L.P');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (742, 'ALDO ', 'MORALES', 'MUÃ‘OZ', '8394721 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (743, 'NELIDA ', 'NINA', 'ROCHA', '9060765 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (744, 'ROGER ARIEL', 'CALLEJAS', 'RODRIGUEZ', '4930491 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (745, 'WILGEN ADONAI', 'CALLEJAS', 'VALENCIA', '4882139 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (746, 'ERNESTINA ', 'COSSIO', 'MAMANI', '8002359 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (747, 'TERSO ', 'EGUINO', 'DURAN', '9912329 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (748, 'ROMELIA ', 'COSSIO', 'MAMANI', '9060720 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (749, 'JAEL ', 'EGUINO', 'DURAN', '9912483 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (750, 'LINET ', 'CALLEJAS', 'RODRIGUEZ', '6999424 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (751, 'PURIFICACION CARLA', 'CALATAYUD', 'FIGUEROA', '9865922 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (752, 'JOSETH ERIKA', 'FLORES', 'VILLAR', '6778371 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (753, 'WILFORD ', 'FLORES', 'VILLAR', '6738353 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (754, 'DORIAN GERMAN', 'GIMENEZ', 'MIRANDA', '9173516 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (755, 'GONZALO ', 'COSSIO', 'MAMANI', '9060517');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (756, 'WILMER ', 'COCA', 'MEJIA', '7291475 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (757, 'MAGDALENA ', 'MAMANI', NULL, '9060632 L.P..');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (758, 'YOYI ', 'LAURA', 'SILES', '4884030 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (759, 'SANDRA ', 'LAURA', 'NAVIA', '4062007 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (760, 'JUAN CARLOS', 'CELIS', 'PAÃ‘UNI', '4308032 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (761, 'JOSE ', 'LUIS', 'MAMANI', '8394715 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (762, 'MARIA MAGDALENA', 'FLORES', 'SANTOS DE CALLE ', '6997056 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (763, 'ARMINDA ', 'LAURA', 'NAVIA', '5773862');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (764, 'LESLY DAYANA', 'LAURA', 'CAMARA', '8365039 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (765, 'SANDRA ', 'CONDORI', 'COLQUE', '10018695 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (766, 'YURI ', 'LUPINTA', 'COSSIO', '8394730 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (767, 'MARY CRUZ', 'COSSIO', 'ZEBALLOS', '9060598 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (768, 'LUIS ', 'PATIÃ‘O', 'COSME', '9060576 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (769, 'MARY ', 'CALLE', 'HUAYTA', '6999423 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (770, 'ELVIS ', 'LAURA', 'MAMANI', '10095620 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (771, 'NICOLI', 'BILBAO', NULL, '4');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (772, 'BORIS ABEL', 'CONDORI', 'CALLEJAS', '9060626 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (773, 'JHOAN PAOLO', 'MIRANDA', 'ARUQUIPA', '8394716 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (774, 'MARCO DANIEL', 'FLORES', 'ARUQUIPA', '8394734 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (775, 'MARISOL ELENA', 'FLORES', 'CONDORI', '9060762 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (776, 'NEIL ', 'AGUIRRE', 'PICAVIA', '8394719 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (777, 'MARCO CAMPOS', NULL, NULL, '3');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (778, 'ELIZABETH ', 'QUITO', 'ZAPATA', '6733789 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (779, 'REYNALDO ', 'LAURA', 'MAMANI', '9721313 SC.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (780, 'MIGUEL ANGEL', 'VALDEZ', 'PICAVIA', '8990797 S.C.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (781, 'LOURDES ', 'COSSIO', 'CEBALLOS', '9060597 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (782, 'LIMBER RENE', 'VEIZAGA', 'MEJIA', '9060541 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (783, 'SANTOS MIGUEL', 'FLORES', 'CONDORI', '9060727 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (784, 'JULIO CESAR', 'ENDARA', 'PEREZ', '15177298 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (785, 'TOMAS ', 'ESPINOZA', 'FERNANDEZ', '12807182 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (786, 'ALEXIA ', 'MIRANDA', 'HUANCA', '8667460 CBBA');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (787, 'SANDRO WINSOR', 'CHOQUE', 'FERNANDEZ', '88183225 CBBA.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (788, 'SANDRO WINSOR', 'CHOQUE', 'FERNANDEZ', '88183225 CBBA');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (789, 'ISABEL ERNESTINA', 'CHOQUE', 'FERNANDEZ', '4059836 OR');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (790, 'SILVIA EUGENIA', 'VALDEZ', 'GUTIERREZ', '6140898 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (791, 'SAMUEL ', 'CHOQUE', 'FERNANDEZ', '4036863 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (792, 'CECILIA ', 'CHOQUE', 'FERNADEZ', '3546522 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (793, 'ROGER EDWIN', 'CHOQUE', 'FERNANDEZ', '5961681 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (794, 'MAGDALENA ', 'SOLARES', 'MAMANI', '6999457 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (795, 'TEODORO ', 'QUIROGA', 'PACHECO', '9912346 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (796, 'CRISTIAN ABRAHAM', 'PAREDEZ', 'MORALES', '11097635 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (797, 'FERNANDO GERARDO', 'ALIAGA', 'ALANOCA', '9061121 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (798, 'ROGER ', 'MARCA', 'CONDORI', '13568161 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (799, 'MARCO GABRIEL', 'CAMPOS', 'RODRIGUEZ', '4886668 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (800, 'BELINDA ROSELIN', 'VALDEZ', 'GUTIERREZ', '10920867 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (801, 'ALFREDO ', 'LAURA', 'MAMANI', '7187676 TJ.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (802, 'ESTEFANI ', 'CALLE', 'FLORES', '8394722 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (803, 'MARIA ', 'CAMPOS', 'RODRIGUEZ', '4886671-1G LP.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (804, 'JHONNY ALDAIR', 'MAMANI', 'AGUIRRE', '12860549 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (805, 'DELIA COSSIO', 'DE', 'GARCIA', '9119732 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (806, 'MARY CELIA', 'BAUTISTA', 'MOLINA', '14041299 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (807, 'JEDWIN RENE', 'CHOQUE', 'FERNANDEZ', '5771431 OR.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (808, 'JOEL ADAN', 'CHOQUE', 'FERNANDEZ', '9060788 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (809, 'FROILAN ', 'FLORES', 'TOCOCOSI', '8445783 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (810, 'ZULMA ', 'JORA', NULL, '2');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (811, 'WILMA MABEL', 'CALLE', 'AGUILAR', '9942198 QR');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (812, 'GROVER ', 'HUARACHI', 'CANAVIRI', '1453688 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (813, 'DIGNA ', 'MAMANI', 'QUISPE', '6161467 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (814, 'RICHARDA ', 'ALAVI', 'GUZMAN', '7423275 OR');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (815, 'MARIO ', 'QUISPE', 'DELGADO', '6699834 PT.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (816, 'JUAN GABRIEL', 'QUISPE', 'MAMANI', '9060502 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (817, 'ALEX VICTOR', 'MAMANI', 'MAMANI', '9069642 L.P.');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (818, 'JUNTA DE', 'VECINOS', NULL, '1');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (819, 'EMMA ', 'CONDORI', 'MARCA', '13567654');
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (820, 'JUNTA DE', 'VECINOS', NULL, NULL);
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (821, 'JUNTA DE', 'VECINOS', NULL, NULL);
INSERT INTO Duenio (id, nombre, paterno, materno, CI) VALUES (822, 'RAUL FERNANDO', 'MORALES', 'SIPE', NULL);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
